---
apiVersion: v1
kind: ConfigMap
metadata:
  name: soundcloud-feeds-config
  namespace: sc-ingest
data:
  # The file path used in sc_ingest.py will be /app/config/feeds.txt
  feeds.txt: |
    https://feeds.soundcloud.com/users/soundcloud:users:345852/sounds.rss
    https://feeds.soundcloud.com/users/soundcloud:users:483960/sounds.rss

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soundcloud-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi