---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sc-ingest-config
  namespace: sc-ingest
data:
  feeds.txt: |
    https://feeds.soundcloud.com/users/soundcloud:users:123456/sounds.rss
    https://feeds.soundcloud.com/users/soundcloud:users:78910/sounds.rss

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-ingest-pvc
  namespace: sc-ingest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi