apiVersion: batch/v1
kind: CronJob
metadata:
  name: sc-ingest-cronjob
  namespace: sc-ingest
spec:
  # Need to be updated to run every week
  schedule: "0 0 29 2 *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: sc-ingest-container
            image: vakintosh/sc-ingest:0.2.1 
            command: ["python3", "main.py"] 
            env:
            - name: DB_PATH 
              value: "/app/data/soundcloud_state.db" 
            - name: FEEDS_CONFIG_PATH 
              value: "/app/config/feeds.txt" 
            resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "250m"
                memory: "256Mi"
            volumeMounts:
            - name: state-volume
              mountPath: /app/data
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          volumes:
          - name: state-volume
            persistentVolumeClaim:
              claimName: sc-ingest-pvc
          - name: config-volume
            configMap:
              name: sc-ingest-config
              items:
              - key: feeds.txt
                path: feeds.txt